
```{r}
library(caret)
library(MLmetrics)
library(partykit)
dataset <- read.csv("C:\\Users\\Pawel Mielniczuk\\Desktop\\Programming\\datascience\\indukcyjne\\glass.csv")
```

```{r}
#F1-Score
f1 <- function(data, lev=NULL, model=NULL) {
  f1_val <- F1_Score(y_pred = data$pred, y_true = data$obs, positive = lev[1])
  c(F1 = f1_val)
}
```

```{r}
dataset$Id <- NULL
head(dataset)
```
```{r}
#contr <- Weka_control(M=5, C=0.3)
#J48(Species~., data=iris, control = contr)
X <- subset(dataset, select = -Class)
Y <- subset(dataset, select = Class)
```

```{r}
m_arr <- c(1, 2, 5, 10, 20, 50)
#m_arr <- c(2)
c_arr <- c(0.005, 0.05, 0.1, 0.25, 0.3, 0.5)
#c_arr <- c(0.25)
best_m <- 0
best_c <- 0
best_f1 <- 0
best_m_s <- 0
best_c_s <- 0
best_f1_s <- 0

folds <- 10
cvIndex <- createFolds(y=as.factor(dataset$Class), k=folds, list = T, returnTrain = T)
stc <- trainControl(index=cvIndex, method='cv', number=folds, summaryFunction=f1)
tc <- trainControl(method='cv', number=folds, summaryFunction=f1)

for (m in m_arr) {
  for (c in c_arr) {
    grid <- expand.grid(M=m, C=c)
    model <- train(x=X, y=as.factor(dataset$Class), method="J48", tuneLength=5, metric="F1", trControl=tc, tuneGrid=grid)

    p <- as.party(model$finalModel)
    size <- length(p)
    leaves <- width(p)
    depth <- depth(p)
    
    print(sprintf("TC F1:%s M:%s C:%s Leaves:%s Size:%s Depth:%s", model$results$F1, model$results$M, model$results$C, leaves, size, depth))

    
    model_s <- train(x=X, y=as.factor(dataset$Class), method="J48", tuneLength=5, metric="F1", trControl=stc, tuneGrid=grid)
    
    p_s <- as.party(model_s$finalModel)
    size_s <- length(p_s)
    leaves_s <- width(p_s)
    depth_s <- depth(p_s)
    
    print(sprintf("STC F1:%s M:%s C:%s Leaves:%s Size:%s Depth:%s", model_s$results$F1, model_s$results$M, model_s$results$C, leaves_s, size_s, depth_s))
    print('')
    
    if (model$results$F1 > best_f1) {
      best_f1 <- model$results$F1
      best_m <- model$results$M
      best_c <- model$results$C
    }
    if (model_s$results$F1 > best_f1_s) {
      best_f1_s <- model_s$results$F1
      best_m_s <- model_s$results$M
      best_c_s <- model_s$results$C
    }
  }
}
print(sprintf("TC BEST F1:%s M:%s C:%s", best_f1, best_m, best_c))
print(sprintf("STC BEST F1:%s M:%s C:%s", best_f1_s, best_m_s, best_c_s))
```

```{r}
folds <- 10
grid <- expand.grid(M=2, C=0.1)
cvIndex <- createFolds(y=as.factor(dataset$Class), k=folds, list = T, returnTrain = T)
stc <- trainControl(index=cvIndex, method='cv', number=folds, summaryFunction=f1)
tc <- trainControl(method='cv', number=folds, summaryFunction=f1)

model <- train(x=X, y=as.factor(dataset$Class), method="J48", tuneLength=5, metric="F1", trControl=tc, tuneGrid=grid)

models <- train(x=X, y=as.factor(dataset$Class), method="J48", tuneLength=5, metric="F1", trControl=stc, tuneGrid=grid)
plot(models$finalModel)
models$results$F1
```

```{r}
#model$results$F1
#summary(model)
#models$results$F1
#summary(models)
print(sprintf("Model %s models %s", model$results$F1, models$results$F1))
p <- as.party(model$finalModel)
size <- length(p)
leaves <- width(p)
depth <- depth(p)
model$finalModel
#best_f1
#best_m
#best_c
#plot(model$finalModel)
```

```{r}
model
varImp(model)
```

